import { NavLink, Outlet, useNavigate } from "react-router-dom";
import { ThemeToggle } from "./ThemeToggle";
import { authApi } from "../../features/auth/contracts";
import { notifyAction } from "../../lib/feedback/actions";

const navigation = [
  { label: "Overview", path: "/admin", group: "Operations" }, { label: "Students", path: "/admin/students", group: "Operations" }, { label: "Activities", path: "/admin/activities", group: "Operations" }, { label: "Sessions", path: "/admin/sessions", group: "Operations" }, { label: "Imports", path: "/admin/imports", group: "Operations" }, { label: "Documents", path: "/admin/documents", group: "Operations" }, { label: "Support requests", path: "/admin/support", group: "Operations" },
  { label: "Signatories", path: "/admin/signatories", group: "Certificate setup" }, { label: "Certificate templates", path: "/admin/templates", group: "Certificate setup", superAdmin: true }, { label: "Leadership templates", path: "/admin/leadership-templates", group: "Certificate setup", superAdmin: true }, { label: "Executive Council certificates", path: "/admin/ec-certificates", group: "Certificate setup", superAdmin: true },
  { label: "Email recovery", path: "/admin/student-recovery", group: "Administration", superAdmin: true }, { label: "Council memberships", path: "/admin/executive-memberships", group: "Administration" }, { label: "Admin accounts", path: "/admin/admins", group: "Administration", superAdmin: true }, { label: "Audit log", path: "/admin/audit", group: "Administration", superAdmin: true },
];
const groups = ["Operations", "Certificate setup", "Administration"];
export function AdminShell({ role }: { role: "ADMIN" | "SUPER_ADMIN" }) {
  const navigate = useNavigate(); const visibleNavigation = navigation.filter((item) => !item.superAdmin || role === "SUPER_ADMIN");
  async function logout() { try { await authApi.logout(); notifyAction("success", "Signed out successfully."); navigate("/"); } catch (error) { notifyAction("error", error instanceof Error ? error.message : "Could not sign out. Please try again."); } }
  return <div className="h-screen overflow-hidden bg-slate-50 text-slate-950 dark:bg-slate-950 dark:text-slate-50"><aside className="fixed inset-y-0 hidden w-64 flex-col border-r border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 xl:flex"><Brand /><div className="admin-scrollbar min-h-0 flex-1 overflow-y-auto"><NavigationGroups items={visibleNavigation} /></div></aside><div className="flex h-full min-w-0 flex-col xl:pl-64"><header className="sticky top-0 z-10 flex min-h-16 flex-none items-center justify-between border-b border-slate-200 bg-white/95 px-4 py-2 backdrop-blur dark:border-slate-800 dark:bg-slate-900/95 sm:px-8"><div className="flex items-center gap-3 xl:hidden"><Brand compact /><details className="relative"><summary className="cursor-pointer rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:border-slate-700">Menu</summary><nav aria-label="Admin navigation" className="absolute left-0 top-11 z-30 max-h-[75vh] w-72 overflow-y-auto rounded-xl border border-slate-200 bg-white p-4 shadow-xl dark:border-slate-700 dark:bg-slate-900"><NavigationGroups items={visibleNavigation} compact /></nav></details></div><div className="ml-auto flex items-center gap-4"><ThemeToggle /><button onClick={() => void logout()} className="rounded text-sm underline focus:outline-none focus:ring-2 focus:ring-indigo-500">Sign out</button><div className="hidden text-right sm:block"><p className="text-sm font-semibold">Admin portal</p><p className="text-xs text-slate-500">EMC Veritas</p></div></div></header><main className="admin-scrollbar min-h-0 flex-1 overflow-y-auto"><div className="mx-auto max-w-7xl p-4 sm:p-8"><Outlet /></div></main></div></div>;
}
function NavigationGroups({ items, compact = false }: { items: typeof navigation; compact?: boolean }) { return <nav aria-label={compact ? undefined : "Admin navigation"} className="mt-6 space-y-6">{groups.map((group) => { const groupItems = items.filter((item) => item.group === group); return groupItems.length ? <section key={group}><h2 className="mb-2 px-3 text-xs font-bold uppercase tracking-wider text-slate-500">{group}</h2><div className="space-y-1">{groupItems.map((item) => <NavigationLink key={item.path} label={item.label} path={item.path} />)}</div></section> : null; })}</nav>; }
function Brand({ compact = false }: { compact?: boolean }) { return <div className="flex items-center gap-3"><img src="/assets/logos/emc-logo.png" alt="Event Management Club" className="h-10 w-10 rounded-xl object-contain" />{!compact && <div><p className="font-bold">EMC Veritas</p><p className="text-xs text-slate-500">Admin workspace</p></div>}</div>; }
function NavigationLink({ label, path }: { label: string; path: string }) { return <NavLink end={path === "/admin"} to={path} className={({ isActive }) => `block rounded-lg px-3 py-2 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500 ${isActive ? "bg-indigo-600 text-white" : "text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"}`}>{label}</NavLink>; }
