import { FormEvent, useState } from "react";
import { authApi } from "./contracts";
import { notifyAction } from "../../lib/feedback/actions";

export function TemporaryPasswordChange({ onComplete }: { onComplete: () => void }) {
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); setSaving(true); try { await authApi.changeTemporaryPassword(currentPassword, newPassword); notifyAction("success", "Password updated successfully."); onComplete(); } catch (caught) { const message = caught instanceof Error ? caught.message : "Password could not be changed."; setError(message); notifyAction("error", message); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><section role="dialog" aria-modal="true" aria-labelledby="password-change-title" className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl dark:bg-slate-900"><h2 id="password-change-title" className="text-xl font-bold">Change temporary password</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">You must choose a new password before using the Admin portal.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-medium">Current password<input required type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} className="mt-1 block w-full rounded border p-2"/></label><label className="block text-sm font-medium">New password<input required minLength={12} type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-1 block w-full rounded border p-2"/></label>{error && <p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={saving} className="w-full rounded bg-indigo-600 p-2 font-semibold text-white">{saving ? "Updating…" : "Update password"}</button></form></section></div>;
}
