import { FormEvent, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest } from "../../lib/api/client";

type IssueResult = { issue_date: string; issued_document_ids: string[]; skipped_student_ids: string[] };
type ReissueResult = { replacement_document_id: string; issue_date: string; version: number };
type DocumentListItem = { id: string; document_type: string; verification_id: string; issue_date: string; status: string; version: number };

export function DocumentsPage() {
  const [activityId, setActivityId] = useState(""); const [documentId, setDocumentId] = useState(""); const [message, setMessage] = useState("");
  const documents = useQuery({ queryKey: ["admin", "documents"], queryFn: () => apiRequest<DocumentListItem[]>("/admin/documents") });
  const issue = useMutation({ mutationFn: () => apiRequest<IssueResult>(`/admin/documents/activities/${activityId}/issue`, { method: "POST" }), onSuccess: (result) => setMessage(`Issued ${result.issued_document_ids.length} records on ${result.issue_date}; ${result.skipped_student_ids.length} existing valid records were skipped.`) });
  const revoke = useMutation({ mutationFn: () => apiRequest<void>(`/admin/documents/${documentId}/revoke`, { method: "POST" }), onSuccess: () => setMessage("Document revoked. It remains available in audit and verification history.") });
  const reissue = useMutation({ mutationFn: () => apiRequest<ReissueResult>(`/admin/documents/${documentId}/reissue`, { method: "POST" }), onSuccess: (result) => setMessage(`New version ${result.version} reserved for ${result.issue_date}: ${result.replacement_document_id}`) });
  function submitIssue(event: FormEvent) { event.preventDefault(); setMessage(""); issue.mutate(); }
  function submitDocument(event: FormEvent, action: "revoke" | "reissue") { event.preventDefault(); setMessage(""); if (action === "revoke") revoke.mutate(); else reissue.mutate(); }
  const error = issue.error?.message ?? revoke.error?.message ?? reissue.error?.message;
  return <section><h1 className="text-3xl font-bold">Document operations</h1><p className="mt-2 text-slate-600 dark:text-slate-400">Issue certificates for an eligible activity, or revoke/reissue an existing document. The backend remains authoritative for templates, signatories, eligibility, and immutable history.</p><form onSubmit={submitIssue} className="mt-6 grid gap-3 rounded-xl border p-4 md:grid-cols-2"><input required value={activityId} onChange={(event) => setActivityId(event.target.value)} placeholder="Activity ID" className="rounded border p-2"/><button disabled={issue.isPending} className="rounded bg-slate-900 p-2 text-white">Issue eligible certificates</button></form><form onSubmit={(event) => submitDocument(event, "reissue")} className="mt-4 grid gap-3 rounded-xl border p-4 md:grid-cols-3"><select required value={documentId} onChange={(event) => setDocumentId(event.target.value)} className="rounded border p-2 md:col-span-1"><option value="">Choose an issued document</option>{documents.data?.map((item) => <option key={item.id} value={item.id}>{item.document_type} · {item.status} · v{item.version} · {item.verification_id}</option>)}</select><button disabled={!documentId || reissue.isPending} className="rounded border p-2">Reissue as new version</button><button type="button" disabled={!documentId || revoke.isPending} onClick={() => revoke.mutate()} className="rounded border border-red-600 p-2 text-red-700">Revoke document</button></form>{documents.error && <p role="alert" className="mt-4 rounded bg-red-50 p-3 text-red-700">{documents.error.message}</p>}{error && <p role="alert" className="mt-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}{message && <p className="mt-4 rounded bg-green-50 p-3 text-green-800">{message}</p>}</section>;
}
