import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Skeleton } from "../../components/ui/Skeleton";
import { apiRequest } from "../../lib/api/client";

type Activity = { id: string; session_id: string; name: string; activity_date: string; status: string };
type Student = { id: string; roll_number: string; full_name: string; active: boolean };
export function ActivitiesPage() {
  const client = useQueryClient(); const [sessionId, setSessionId] = useState(""); const [name, setName] = useState(""); const [date, setDate] = useState(""); const [activityId, setActivityId] = useState(""); const [studentId, setStudentId] = useState("");
  const activities = useQuery({ queryKey: ["admin", "activities"], queryFn: () => apiRequest<Activity[]>("/admin/activities") });
  const students = useQuery({ queryKey: ["admin", "students"], queryFn: () => apiRequest<Student[]>("/admin/students") });
  const refresh = () => client.invalidateQueries({ queryKey: ["admin", "activities"] });
  const create = useMutation({ mutationFn: () => apiRequest<Activity>("/admin/activities", { method: "POST", body: JSON.stringify({ session_id: sessionId, name, activity_date: date }) }), onSuccess: () => { setName(""); setDate(""); void refresh(); } });
  const setStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => apiRequest<Activity>(`/admin/activities/${id}/status`, { method: "POST", body: JSON.stringify({ status }) }), onSuccess: () => void refresh() });
  const issue = useMutation({ mutationFn: (id: string) => apiRequest(`/admin/documents/activities/${id}/issue`, { method: "POST" }), onSuccess: () => void refresh() });
  const addParticipant = useMutation({ mutationFn: () => apiRequest(`/admin/activities/${activityId}/participants`, { method: "POST", body: JSON.stringify({ student_id: studentId, eligible: true }) }), onSuccess: () => { setStudentId(""); } });
  function createActivity(event: FormEvent) { event.preventDefault(); create.mutate(); }
  function addToActivity(event: FormEvent) { event.preventDefault(); addParticipant.mutate(); }
  return <section><h1 className="text-3xl font-bold">Activities</h1><p className="mt-2 text-slate-600 dark:text-slate-400">Create activities under a session, manage participants, and use explicit status changes.</p><form onSubmit={createActivity} className="mt-6 grid gap-3 rounded-xl border p-4 md:grid-cols-4"><input required placeholder="Session ID" value={sessionId} onChange={(e) => setSessionId(e.target.value)} className="rounded border p-2"/><input required placeholder="Activity name" value={name} onChange={(e) => setName(e.target.value)} className="rounded border p-2"/><input required type="date" value={date} onChange={(e) => setDate(e.target.value)} className="rounded border p-2"/><button disabled={create.isPending} className="rounded bg-slate-900 p-2 text-white">Create activity</button>{create.isError && <p role="alert" className="text-red-700 md:col-span-4">{create.error.message}</p>}</form><form onSubmit={addToActivity} className="mt-4 grid gap-3 rounded-xl border p-4 md:grid-cols-3"><select required value={activityId} onChange={(e) => setActivityId(e.target.value)} className="rounded border p-2"><option value="">Choose activity</option>{activities.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required value={studentId} onChange={(e) => setStudentId(e.target.value)} className="rounded border p-2"><option value="">Choose active student</option>{students.data?.filter((student) => student.active).map((student) => <option key={student.id} value={student.id}>{student.roll_number} — {student.full_name}</option>)}</select><button disabled={addParticipant.isPending} className="rounded bg-slate-900 p-2 text-white">Add eligible participant</button>{addParticipant.isError && <p role="alert" className="text-red-700 md:col-span-3">{addParticipant.error.message}</p>}</form>{issue.isError && <p role="alert" className="mt-3 text-red-700">{issue.error.message}</p>}{activities.isLoading ? <Skeleton className="mt-6 h-40 w-full"/> : activities.isError ? <p role="alert" className="mt-6 text-red-700">{activities.error.message}</p> : <ul className="mt-6 space-y-3">{activities.data?.map((item) => <li key={item.id} className="rounded border p-4"><strong>{item.name}</strong> — {item.activity_date} — {item.status}<select aria-label={`Change status for ${item.name}`} className="ml-4 rounded border p-1" value={item.status} onChange={(event) => setStatus.mutate({ id: item.id, status: event.target.value })}><option>DRAFT</option><option>READY</option><option>PUBLISHED</option><option>ARCHIVED</option></select><button onClick={() => issue.mutate(item.id)} disabled={issue.isPending || item.status === "ARCHIVED"} className="ml-3 underline">Issue eligible certificates</button></li>)}</ul>}</section>;
}
