import { lazy, Suspense } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { Skeleton } from "../../components/ui/Skeleton";
import { apiRequest } from "../../lib/api/client";

type Student = { active: boolean };
type EmcSession = { id: string; name: string; start_date: string; end_date: string; status: string };
type Activity = { id: string; name: string; status: string };
type DocumentListItem = { id: string; student_id: string; activity_id: string | null; document_type: string; issue_date: string; status: string };
const ActivityChart = lazy(() => import("./ActivityChart"));
const statuses = ["DRAFT", "READY", "PUBLISHED", "ARCHIVED"];
export function validDocuments(documents: DocumentListItem[]) { return documents.filter((document) => document.status === "VALID"); }
export function certificateRecipientCount(documents: DocumentListItem[]) { return new Set(validDocuments(documents).map((document) => document.student_id)).size; }
function Retry({ onRetry }: { onRetry: () => void }) { return <button type="button" onClick={onRetry} className="mt-2 rounded border border-red-300 px-3 py-1.5 text-sm font-semibold text-red-800 focus:outline-none focus:ring-2 focus:ring-red-500 dark:border-red-900 dark:text-red-200">Retry</button>; }

export function AdminDashboard() {
  const students = useQuery({ queryKey: ["admin", "students"], queryFn: () => apiRequest<Student[]>("/admin/students") });
  const sessions = useQuery({ queryKey: ["admin", "sessions"], queryFn: () => apiRequest<EmcSession[]>("/admin/sessions") });
  const activities = useQuery({ queryKey: ["admin", "activities"], queryFn: () => apiRequest<Activity[]>("/admin/activities") });
  const documents = useQuery({ queryKey: ["admin", "documents"], queryFn: () => apiRequest<DocumentListItem[]>("/admin/documents") });
  const valid = validDocuments(documents.data ?? []); const activeSession = (sessions.data ?? []).find((session) => session.status === "ACTIVE");
  const chart = statuses.map((status) => ({ status, count: (activities.data ?? []).filter((item) => item.status === status).length }));
  const attention = chart.find((item) => item.status === "DRAFT")!.count + chart.find((item) => item.status === "READY")!.count;
  const activityNames = new Map((activities.data ?? []).map((activity) => [activity.id, activity.name]));
  const recentDocuments = [...valid].sort((a, b) => b.issue_date.localeCompare(a.issue_date)).slice(0, 5);
  const refreshedAt = [students, sessions, activities, documents].map((query) => query.dataUpdatedAt).filter(Boolean); const lastRefreshed = refreshedAt.length ? new Date(Math.max(...refreshedAt)).toLocaleString() : null;
  const metricCards = [{ label: "Certificate recipients", value: certificateRecipientCount(documents.data ?? []), helper: "Unique students with a valid certificate", query: documents }, { label: "Certificates issued", value: valid.length, helper: "Currently valid certificate records", query: documents }, { label: "Total activities", value: activities.data?.length ?? 0, helper: "All lifecycle statuses", query: activities }];
  return <motion.section aria-labelledby="admin-overview" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.18 }}>
    <div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-medium text-indigo-600 dark:text-indigo-400">Operations</p><h1 id="admin-overview" className="mt-1 text-3xl font-bold tracking-tight">Admin overview</h1><p className="mt-2 max-w-2xl text-slate-600 dark:text-slate-400">Current outcomes, operational work, and direct paths to the next task.</p></div><p className="text-xs text-slate-500">{lastRefreshed ? `Last refreshed ${lastRefreshed}` : "Waiting for the first successful refresh"}</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metricCards.map(({ label, value, helper, query }) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-sm font-medium text-slate-500">{label}</p>{query.isLoading ? <Skeleton className="mt-4 h-8 w-20" /> : query.isError ? <div role="alert" className="mt-3 text-sm text-red-700 dark:text-red-300">Could not load.<Retry onRetry={() => void query.refetch()} /></div> : <><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{helper}</p></>}</article>)}<article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-sm font-medium text-slate-500">Active session</p>{sessions.isLoading ? <Skeleton className="mt-4 h-8 w-32" /> : sessions.isError ? <div role="alert" className="mt-3 text-sm text-red-700 dark:text-red-300">Could not load.<Retry onRetry={() => void sessions.refetch()} /></div> : activeSession ? <><p className="mt-3 text-lg font-bold">{activeSession.name}</p><p className="mt-1 text-xs text-slate-500">{activeSession.start_date} to {activeSession.end_date}</p></> : <><p className="mt-3 text-lg font-bold">No active session</p><p className="mt-1 text-xs text-slate-500">Create or activate a session to start activity work.</p></>}</article></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1.4fr_1fr]"><section aria-label="Activity lifecycle" className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><h2 className="font-semibold">Activity lifecycle</h2><p className="mt-1 text-sm text-slate-500">{attention} {attention === 1 ? "activity" : "activities"} needing attention (Draft or Ready).</p></div>{activities.isSuccess && <p className="text-sm text-slate-500">{students.data?.filter((student) => student.active).length ?? 0} active students</p>}</div>{activities.isLoading ? <Skeleton className="mt-5 h-56 w-full" /> : activities.isError ? <div role="alert" className="mt-5 rounded-lg bg-red-50 p-4 text-red-700 dark:bg-red-950/30 dark:text-red-200">Activity lifecycle is unavailable.<Retry onRetry={() => void activities.refetch()} /></div> : <Suspense fallback={<Skeleton className="mt-5 h-56 w-full" />}><ActivityChart data={chart} /></Suspense>}</section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Quick actions</h2><p className="mt-1 text-sm text-slate-500">Continue an existing workflow.</p><div className="mt-4 grid gap-2"><Link className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-indigo-500" to="/admin/activities">Manage activities</Link><Link className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:border-slate-700" to="/admin/documents">Issue documents</Link><Link className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:border-slate-700" to="/admin/students">Review students</Link></div></section></div>
    <section className="mt-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Recent certificates</h2><p className="mt-1 text-sm text-slate-500">Latest currently valid document records.</p></div><Link to="/admin/documents" className="text-sm font-semibold text-indigo-700 underline focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:text-indigo-300">View documents</Link></div>{documents.isLoading ? <Skeleton className="mt-4 h-36 w-full" /> : documents.isError ? <div role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-700 dark:bg-red-950/30 dark:text-red-200">Recent certificates are unavailable.<Retry onRetry={() => void documents.refetch()} /></div> : !recentDocuments.length ? <p className="mt-4 rounded-lg border border-dashed p-4 text-sm text-slate-500">No valid certificates have been issued yet.</p> : <ul className="mt-4 divide-y divide-slate-200 dark:divide-slate-800">{recentDocuments.map((document) => <li key={document.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><div><p className="font-medium">{document.document_type}</p><p className="text-slate-500">{document.activity_id ? activityNames.get(document.activity_id) ?? "Associated activity" : "No activity association"} · Issued {document.issue_date}</p></div><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">VALID</span></li>)}</ul>}</section>
  </motion.section>;
}
