"""add template fonts

Revision ID: edb2eefdb003
Revises: a5cdc1687e49
Create Date: 2026-09-24 02:54:42.505025
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb2eefdb003'
down_revision: Union[str, Sequence[str], None] = 'a5cdc1687e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_fonts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_template_fonts_template_id'), 'template_fonts', ['template_id'], unique=False)
    op.add_column('template_fields', sa.Column('custom_font_storage_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_fields', 'custom_font_storage_key')
    op.drop_index(op.f('ix_template_fonts_template_id'), table_name='template_fonts')
    op.drop_table('template_fonts')
    # ### end Alembic commands ###
