import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Skeleton } from "../../components/ui/Skeleton";
import { apiRequest } from "../../lib/api/client";

type Signatory = { id: string; name: string; official_title: string; effective_start_date: string; effective_end_date: string | null; active: boolean };

export function SignatoriesPage() {
  const client = useQueryClient();
  const [name, setName] = useState(""); const [title, setTitle] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [signature, setSignature] = useState<File | null>(null);
  const query = useQuery({ queryKey: ["admin", "signatories"], queryFn: () => apiRequest<Signatory[]>("/admin/signatories") });
  const refresh = () => client.invalidateQueries({ queryKey: ["admin", "signatories"] });
  const create = useMutation({ mutationFn: () => { const data = new FormData(); data.append("name", name); data.append("official_title", title); data.append("effective_start_date", start); if (end) data.append("effective_end_date", end); if (signature) data.append("signature", signature); return apiRequest<Signatory>("/admin/signatories", { method: "POST", body: data }); }, onSuccess: () => { setName(""); setTitle(""); setStart(""); setEnd(""); setSignature(null); void refresh(); } });
  const deactivate = useMutation({ mutationFn: (id: string) => apiRequest<Signatory>(`/admin/signatories/${id}/deactivate`, { method: "POST" }), onSuccess: () => void refresh() });
  function submit(event: FormEvent) { event.preventDefault(); if (signature) create.mutate(); }
  return <section><h1 className="text-3xl font-bold">Signatories</h1><p className="mt-2 text-slate-600 dark:text-slate-400">Maintain effective-dated signing authority. Historical records stay available and are never deleted.</p><form onSubmit={submit} className="mt-6 grid gap-3 rounded-xl border p-4 md:grid-cols-3"><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Full name" className="rounded border p-2"/><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Official title, e.g. President" className="rounded border p-2"/><input required type="file" accept="image/png,image/jpeg" onChange={(e) => setSignature(e.target.files?.[0] ?? null)} className="rounded border p-2"/><input required type="date" value={start} onChange={(e) => setStart(e.target.value)} className="rounded border p-2"/><input type="date" value={end} onChange={(e) => setEnd(e.target.value)} className="rounded border p-2"/><button disabled={create.isPending || !signature} className="rounded bg-slate-900 p-2 text-white">Add signatory</button>{create.isError && <p role="alert" className="text-red-700 md:col-span-3">{create.error.message}</p>}</form>{query.isLoading ? <Skeleton className="mt-6 h-48 w-full"/> : query.isError ? <p role="alert" className="mt-6 text-red-700">{query.error.message}</p> : <div className="mt-6 overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Name</th><th className="p-3">Title</th><th className="p-3">Effective dates</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{query.data?.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-3">{item.name}</td><td className="p-3">{item.official_title}</td><td className="p-3">{item.effective_start_date} — {item.effective_end_date ?? "Open-ended"}</td><td className="p-3">{item.active ? "Active" : "Historical"}</td><td className="p-3">{item.active && <button onClick={() => deactivate.mutate(item.id)} disabled={deactivate.isPending} className="underline">Deactivate</button>}</td></tr>)}</tbody></table></div>}</section>;
}
